name: CreateBucket Main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.GoogleCloudStorage.CreateBucket/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.GoogleCloudStorage.CreateBucket
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}