name: CreateBucket build test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.GoogleCloudStorage.CreateBucket/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.GoogleCloudStorage.CreateBucket
      env_var_name_1: Frends_GoogleCloudStorage_CredJson
      prebuild_command: echo ${{ secrets.env_var_value_1 }} | base64 -d > credentials.json
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.FRENDS_GOOGLECLOUDSTORAGE_CREDJSON }}