name: CreateBucket build test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.GoogleCloudStorage.CreateBucket/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.GoogleCloudStorage.CreateBucket
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}