name: DownloadObject build test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.GoogleCloudStorage.DownloadObject/**'
  workflow_dispatch:

jobs:
  windows-build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.GoogleCloudStorage.DownloadObject
      env_var_name_1: Frends_GoogleCloudStorage_CredJson
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.FRENDS_GOOGLECLOUDSTORAGE_CREDJSON }}
  linux-build:
    needs: windows-build
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.GoogleCloudStorage.DownloadObject
      env_var_name_1: Frends_GoogleCloudStorage_CredJson
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.FRENDS_GOOGLECLOUDSTORAGE_CREDJSON }}